proton: "ServiceSpec"
pipeline:
  dockerfile: "Dockerfile"
  buildspecfile: "containerized-saas-application/buildspec.yml"
  totalwaves: 1
instances:
- name: "tenantA-saas-app"
  environment: "tenantAEnv"
  spec:
    service_discovery_name: "t1.saasapp.com"
    load_balanced: true
    load_balanced_public: true
    image: "public.ecr.aws/nginx/nginx:stable"